AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate service for StreamLit/FastAPI application'

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String
    Default: dev
  
  ApplicationName:
    Description: Application name
    Type: String
    Default: myapp

  ImageURI:
    Description: ECR image URI to deploy
    Type: String

  DesiredCount:
    Description: Number of tasks to run
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${EnvironmentName}-${ApplicationName}-cluster'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-${ApplicationName}-cluster'

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${EnvironmentName}-${ApplicationName}'
      RetentionInDays: 7

  # ECS Task Execution Role
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-${ApplicationName}-task-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'

  # ECS Task Role (for the application itself)
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${EnvironmentName}-${ApplicationName}-task-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LogGroup.Arn

  # ECS Task Definition
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${EnvironmentName}-${ApplicationName}'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub '${EnvironmentName}-${ApplicationName}-container'
          Image: !Ref ImageURI
          Essential: true
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
              Name: fastapi
            - ContainerPort: 8501
              Protocol: tcp
              Name: streamlit
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ENV
              Value: !Ref EnvironmentName
            - Name: API_BASE_URL
              Value: !Sub
                - 'http://${ALBDNSName}'
                - ALBDNSName:
                    Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-ALB-DNS'
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8000/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - FastAPIListenerRule
      - StreamlitListenerRule
    Properties:
      ServiceName: !Sub '${EnvironmentName}-${ApplicationName}-service'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: !Ref DesiredCount
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-ECSSecurityGroup'
          Subnets:
            - Fn::Select:
                - 0
                - Fn::Split:
                    - ","
                    - Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-PrivateSubnets'
            - Fn::Select:
                - 1
                - Fn::Split:
                    - ","
                    - Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-PrivateSubnets'
          AssignPublicIp: DISABLED
      LoadBalancers:
        - TargetGroupArn:
            Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-FastAPITargetGroup'
          ContainerName: !Sub '${EnvironmentName}-${ApplicationName}-container'
          ContainerPort: 8000
        - TargetGroupArn:
            Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-StreamlitTargetGroup'
          ContainerName: !Sub '${EnvironmentName}-${ApplicationName}-container'
          ContainerPort: 8501
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      EnableExecuteCommand: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-${ApplicationName}-service'

  # ALB Listener Rules
  FastAPIListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-FastAPITargetGroup'
      Conditions:
        - Field: path-pattern
          Values: ["/api/*", "/docs", "/redoc", "/openapi.json", "/health"]
      ListenerArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-HTTPListener'
      Priority: 100

  StreamlitListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn:
            Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-StreamlitTargetGroup'
      Conditions:
        - Field: path-pattern
          Values: ["/*"]
      ListenerArn:
        Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-HTTPListener'
      Priority: 200

  # Auto Scaling
  ServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Sub 'service/${ECSCluster}/${ECSService.Name}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${EnvironmentName}-${ApplicationName}-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ServiceScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleOutCooldown: 300
        ScaleInCooldown: 300

Outputs:
  ECSCluster:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${EnvironmentName}-${ApplicationName}-ECSCluster'

  ECSService:
    Description: ECS Service Name
    Value: !Ref ECSService
    Export:
      Name: !Sub '${EnvironmentName}-${ApplicationName}-ECSService'

  TaskDefinition:
    Description: ECS Task Definition ARN
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub '${EnvironmentName}-${ApplicationName}-TaskDefinition'

  FastAPIURL:
    Description: FastAPI URL
    Value: !Sub
      - 'http://${ALBDNSName}/docs'
      - ALBDNSName:
          Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-ALB-DNS'
    Export:
      Name: !Sub '${EnvironmentName}-${ApplicationName}-FastAPIURL'

  StreamlitURL:
    Description: Streamlit URL
    Value: !Sub
      - 'http://${ALBDNSName}/'
      - ALBDNSName:
          Fn::ImportValue: !Sub '${EnvironmentName}-${ApplicationName}-ALB-DNS'
    Export:
      Name: !Sub '${EnvironmentName}-${ApplicationName}-StreamlitURL'